### ISSUE TITLE
Allow YAML usual extensions for graph metadata files

### ISSUE THREAD

**Issue by alexprengere** [AmadeusITGroup/GraphDash#2]
Currently, the process to build the website is:
- in the `root` directory, look for all `txt` files containing valid metadata (YAML syntax, top level dict)
- build the tree of graphs from the metadata, configuration files and command line arguments
- start the webserver

As some people pointed out, it is strange `txt` extension is used for metadata files and not `yaml` or `yml`. The rationale is that once the website is started, all files in `root` are served using the the `data` route, including the metadata. When debugging, you can display the metadata in the browser, and `txt` files are shown as is, whereas `yaml` files are dowloaded and have to be opened from a third party program. On the other hand, using the correct extension allows syntax highlighting in editors and feels more natural.

I think  `GraphDash` could support both extensions for metadata. It would look for either `txt`, `yaml` and `yml` as metadata files (case insentitive). This would avoid backward incompatilibity. Most of the work is updating the documentation and examples though.

**Comment by claudex** [comment]
> When debugging, you can display the metadata in the browser, and txt files are shown as is, whereas yaml files are dowloaded and have to be opened from a third party program

If you set the mime type to text/plain, it won't be downloaded but printed in the browser as with the `txt` extension.

**Comment by alexprengere** [comment]
@claudex you are right, I fixed the mimetypes with bbb831d5e0bd9b2bc77adf11b13b42947c29387b.

Otherwise I will close the issue, the relevant commits being:
- df144460a5a08fadcc202eb23866f72d7bd7925f for the loading of `yaml` and `yml` files
- 388a64c4d8ce61a018064ab4f95134ead7889f15 for the loading of the families file
- c4f838d5b289f75ad5d6949ec54c07a5eda1c7d9 for the docs
