### ISSUE TITLE
`( ) No configuration file provided`

### ISSUE THREAD

**Issue by jpskycak** [AmadeusITGroup/GraphDash#3]
Sorry if this is simple, but I'm pretty new to the software world. When I start up GraphDash locally, I receive a command line message `( ) No configuration file provided`. However, I am able to view the unconfigured site at http://0.0.0.0:5555/. The graphs load, too: `( ) 3 graphs loaded from /Users/jskycak/Desktop/graphdash/default_graph_dir`. 

![screen shot 2016-07-11 at 12 35 30 pm](https://cloud.githubusercontent.com/assets/13306854/16738598/5eee3a94-4764-11e6-9caf-6b6fd4687f14.png)

The config file is `docs/graphdash.yaml`, right? It includes `root: ../default_graph_dir`, which makes sense to me... Why can't GraphDash find the config file?

**Comment by jpskycak** [comment]
Never mind, just needed to use GraphDash -c docs/graphdash.yaml, as explained in the README.

**Comment by alexprengere** [comment]
Hello! Indeed the default `root` is `default_graph_dir`, but there is no default configuration file.
Since you did not provide any options, the graphs were loaded properly from `default_graph_dir`, but you got a message informing you that no configuration file was set.
