### ISSUE TITLE
PNG not loading properly with Chrome

### ISSUE THREAD

**Issue by pierrelesesvre** [AmadeusITGroup/GraphDash#4]
My .png are not loading until I resize or refresh the page.
This issue only seems to happen with Chrome, it could come from Lazyloading.

**Comment by alexprengere** [comment]
Indeed, it looks like the [lazyload](https://github.com/verlok/lazyload) plugin needs to be updated to work with the latest Chrome.

Fixed with 127fa015e02e65b2694de08398921405656d9a09, new [PyPI release](https://pypi.org/project/GraphDash) pushed.

**Comment by pierrelesesvre** [comment]
Problem solved. Thanks for your reactivity.
